{{/*
This template conditionally enables Redis based on the customer operation pattern.
The Chart.yaml dependency condition will use redis.enabled from the merged values.
*/}}
{{- if eq .Values.config.customerOperation.pattern "Async" -}}
{{- $_ := set .Values.redis "enabled" true -}}
{{- $_ := set .Values.config.distributedCache "enabled" true -}}
{{- else -}}
{{- $_ := set .Values.redis "enabled" false -}}
{{- $_ := set .Values.config.distributedCache "enabled" false -}}
{{- end -}}