{{- if and .Values.sqlserver.enabled .Values.sqlserver.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "reliability-demo.fullname" . }}-sqlserver-pvc
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.sqlserver.persistence.storageClass }}
  storageClassName: {{ .Values.sqlserver.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.sqlserver.persistence.size }}
{{- end }}