apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reliability-demo.fullname" . }}
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "reliability-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        configmap/checksum: {{ include (print $.Template.BasePath "/web-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "reliability-demo.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        {{- if eq .Values.architecture.nodeArch "arm64" }}
        nodepool: arm64
        {{- else }}
        nodepool: default
        {{- end }}
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
      {{- if eq .Values.architecture.nodeArch "arm64" }}
        - key: "nodepool"
          operator: "Equal"
          value: "arm64"
          effect: "NoSchedule"
      {{- end }}
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageRegistry.domain }}/{{ .Values.imageRegistry.repository }}/{{ .Values.web.image.imageName }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ include "reliability-demo.fullname" . }}-config: config-volume
              mountPath: /app/config
              readOnly: true
          {{- if .Values.web.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.web.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.web.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.web.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "reliability-demo.fullname" . }}-web-config