# K6 Test Suite Configuration for Azure Demo
# This file only overrides values that differ from the base values.yaml

# Target application configuration for Azure
target:
  service: "reliability-demo.reliability-demo.svc.cluster.local"
  port: 80

# Extended test configuration for Azure demo
tests:
  sequential:
    activeDeadlineSeconds: 1800  # 30 minutes timeout
    
    # Increased resources for longer tests
    resources:
      requests:
        memory: "1G" 
        cpu: "500m"
      limits:
        memory: "2G"
        cpu: "1"
    
    # Schedule K6 on AMD64 nodes
    nodeSelector:
      kubernetes.io/arch: amd64
      nodepool: default
    
    # Azure demo test sequence
    sequence:
      - name: "Soak Test"
        script: "customer-soak-test.js"
        duration: "10m"
        description: "40 constant users testing GET /api/customers for 10 minutes"
      - name: "Load Test"
        script: "customer-load-test.js" 
        duration: "5m"
        description: "Ramping load creating customers (10→30→70→50→10 users) for 5 minutes"
      - name: "Spike Test"
        script: "customer-spike-test.js"
        duration: "5m"
        description: "Aggressive spike to 600 users for 5 minutes to test system limits"

# Azure demo test parameters
scripts:
  # Soak test - 10 minutes with 40 VUs
  soak:
    scenarios:
      vus: 40
      duration: "10m"
  
  # Load test - 5m ramping load
  load:
    scenarios:
      stages:
        - duration: "30s"
          target: 10
        - duration: "1m"
          target: 30
        - duration: "2m"
          target: 70
        - duration: "1m"
          target: 50
        - duration: "30s"
          target: 10
  
  # Spike test - 5m, aggressive spike to test failure
  spike:
    scenarios:
      stages:
        - duration: "30s"
          target: 15
        - duration: "15s"
          target: 600
        - duration: "3m"
          target: 600
        - duration: "15s"
          target: 15
        - duration: "1m"
          target: 15