apiVersion: v1
kind: ConfigMap
metadata:
  name: reliability-demo-config
  namespace: reliability-demo
data:
  shared.json: |
    {
      "ConnectionStrings": {
        "SqlServer": "Server=sqlserver;Database=ReliabilityDemo;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true",
        "Redis": "redis:6379"
      },
      "DataStore": {
        "Provider": "SqlServer"
      },
      "DistributedCache": {
        "Enabled": true
      },
      "CustomerOperation" : {
        "Pattern": "Async"
      },
      "Logging": {
        "Console": {
          "FormatterName": "json",
          "IncludeScopes": true,
          "TimestampFormat": "HH:mm:ss.fff"
        }
      }
    }