apiVersion: apps/v1
kind: Deployment
metadata:
  name: reliability-demo-web
  namespace: reliability-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reliability-demo
      component: web
  template:
    metadata:
      labels:
        app: reliability-demo
        component: web
    spec:
      containers:
      - name: web
        image: sixeyed/reliability-demo:m1-01
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: reliability-demo-config
---
apiVersion: v1
kind: Service
metadata:
  name: reliability-demo-web
  namespace: reliability-demo
spec:
  type: LoadBalancer
  selector:
    app: reliability-demo
    component: web
  ports:
  - port: 8080
    targetPort: 8080