# Local development overrides for Reliability Demo application

# Web API configuration for local development
web:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 8080  # Local uses port 8080
    targetPort: 8080
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  livenessProbe:
    initialDelaySeconds: 15
  readinessProbe:
    initialDelaySeconds: 10
  podDisruptionBudget:
    enabled: false  # Not needed for local development
  autoscaling:
    enabled: false  # Use fixed replicas locally

# Worker configuration for local development
worker:
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  podDisruptionBudget:
    enabled: false
  autoscaling:
    enabled: false

# Application configuration for local development
config:
  distributedCache:
    expirationSeconds: 60  # Shorter cache for development
  messaging:
    retryDelayMs: 500  # Faster retries for development

# Redis configuration for local development
redis:
  master:
    persistence:
      enabled: false  # No persistence needed locally
  replica:
    replicaCount: 0  # No replicas needed locally

# SQL Server configuration for local development
sqlserver:
  persistence:
    size: 1Gi  # Smaller volume for local