apiVersion: v1
kind: Service
metadata:
  name: {{ include "reliability-demo.fullname" . }}-web
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "reliability-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web