apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reliability-demo.fullname" . }}-worker
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "reliability-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "reliability-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: worker
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ConnectionStrings__SqlServer
          value: "Server={{ include "reliability-demo.fullname" . }}-sqlserver,1433;Database=ReliabilityDemo;User Id=sa;Password={{ .Values.sqlserver.auth.saPassword }};TrustServerCertificate=true"
        - name: ConnectionStrings__Redis
          value: "{{ include "reliability-demo.fullname" . }}-redis-master:6379"
        - name: DataStore__Provider
          value: {{ .Values.config.dataStore.provider | quote }}
        - name: SqlServerDataStore__MaxConcurrentClients
          value: {{ .Values.config.sqlServerDataStore.maxConcurrentClients | quote }}
        - name: SqlServerDataStore__AutoMigrate
          value: {{ .Values.config.sqlServerDataStore.autoMigrate | quote }}
        - name: RedisDataStore__MaxConcurrentClients
          value: {{ .Values.config.redisDataStore.maxConcurrentClients | quote }}
        - name: Messaging__Enabled
          value: {{ .Values.config.messaging.enabled | quote }}
        - name: Messaging__CustomerChannelName
          value: {{ .Values.config.messaging.customerChannelName | quote }}
        - name: Messaging__RetryAttempts
          value: {{ .Values.config.messaging.retryAttempts | quote }}
        - name: Messaging__RetryDelayMs
          value: {{ .Values.config.messaging.retryDelayMs | quote }}
        {{- with .Values.worker.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.worker.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}