apiVersion: apps/v1
kind: Deployment
metadata:
  name: reliability-demo-web
  namespace: reliability-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reliability-demo
      component: web
  template:
    metadata:
      labels:
        app: reliability-demo
        component: web
    spec:
      containers:
      - name: web
        image: alpine:latest
        command: ["sleep", "infinity"]
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "1000m"
          limits:
            memory: "0.5Gi"
            cpu: "2000m"
      volumes:
      - name: config
        configMap:
          name: reliability-demo-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reliability-demo-config
  namespace: reliability-demo
data:
  shared.json: |
    {
      "ConnectionStrings": {
        "SqlServer": "Server=sqlserver;Database=ReliabilityDemo;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true",
        "Redis": "redis:6379"
      },
      "DataStore": {
        "Provider": "SqlServer"
      },
      "DistributedCache": {
        "Enabled": true
      },
      "CustomerOperation" : {
        "Pattern": "Async"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.EntityFrameworkCore": "Warning",
          "ReliabilityDemo": "Debug"
        },
        "Console": {
          "FormatterName": "json",
          "IncludeScopes": true,
          "TimestampFormat": "HH:mm:ss.fff"
        }
      }
    }
