apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reliability-demo.fullname" . }}-config
  labels:
    {{- include "reliability-demo.labels" . | nindent 4 }}
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "ReliabilityDemo.Services.FailureSimulator": "Debug",
          "ReliabilityDemo.Controllers": "Debug",
          "Microsoft.AspNetCore": "Warning"
        },
        "Console": {
          "IncludeScopes": false,
          "TimestampFormat": "HH:mm:ss "
        }
      },
      "FailureConfig": {
        "ConnectionFailureRate": {{ .Values.config.failureConfig.connectionFailureRate | float64 }},
        "ReadTimeoutRate": {{ .Values.config.failureConfig.readTimeoutRate | float64 }},
        "WriteTimeoutRate": {{ .Values.config.failureConfig.writeTimeoutRate | float64 }},
        "SlowResponseRate": {{ .Values.config.failureConfig.slowResponseRate | float64 }},
        "ReadTimeoutMs": {{ .Values.config.failureConfig.readTimeoutMs | int }},
        "WriteTimeoutMs": {{ .Values.config.failureConfig.writeTimeoutMs | int }},
        "SlowResponseDelayMs": {{ .Values.config.failureConfig.slowResponseDelayMs | int }}
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "Redis": "{{ .Release.Name }}-redis-master:6379",
        "SqlServer": "{{ include "reliability-demo.sqlServerConnectionString" . }}"
      },
      "DataStore": {
        "Provider": "{{ .Values.config.dataStore.provider }}"
      },
      "RedisDataStore": {
        "MaxConcurrentClients": {{ .Values.config.redisDataStore.maxConcurrentClients | int }}
      },
      "SqlServerDataStore": {
        "MaxConcurrentClients": {{ .Values.config.sqlServerDataStore.maxConcurrentClients | int }},
        "AutoMigrate": {{ .Values.config.sqlServerDataStore.autoMigrate }}
      }
    }