apiVersion: v2
name: reliability-demo
description: A Helm chart for the Reliability Demo application showcasing GitOps best practices
type: application
version: 1.0.0
appVersion: "v1.0.0"
home: https://github.com/sixeyed/ps-sre3-demo2
maintainers:
  - name: SRE Team
    email: sre@example.com
keywords:
  - reliability
  - demo
  - gitops
  - kubernetes
dependencies:
  - name: redis
    version: "18.1.5"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: sqlserver
    version: "1.0.0" 
    repository: "file://charts/sqlserver"
    condition: sqlserver.enabled